README.md changes
0chain/minio pull request #54
Opened 2023-08-04 18:03 UTC by hm90121

- added table of contents
- corrected typos and added links
- added zus overview
still a work in progress

2023-08-05 07:42 UTC, boddumanohar approved these changes

2023-09-22 18:59 UTC, Kishan-Dhakan requested changes

2023-09-22 18:59 UTC, Kishan-Dhakan commented on README.md
> +Prerequisites to run MinIO ZCN gateway: [wallet.json can be created using zwalletcli](https://github.com/0chain/zwalletcli#creating-and-restoring-wallets), [config.yaml](https://github.com/0chain/zbo
Please write these as different points/steps rather than one comma separated sentence.

2023-09-22 18:59 UTC, Kishan-Dhakan commented on README.md
> +To build and run minio server component you need to first install [docker](https://www.docker.com/products/docker-desktop/).
To build and run `the`

2023-09-22 18:59 UTC, Kishan-Dhakan commented on README.md
> +3. Run the docker-compose command inside the zs3server directory.
Change 3. to 2.

2023-09-22 18:59 UTC, Kishan-Dhakan commented on README.md
> +To build and run minio server component you need to first install [docker](https://www.docker.com/products/docker-desktop/).
remove the `first`

2023-09-22 19:25 UTC, stewartie4 reviewed
Happy to merge minus Kishan's comments

2023-09-26 07:59 UTC, hm90121 commented
@Kishan-Dhakan i have included your suggestions but this PR is quite old i had all of the suggested changes as a new readme with it. Share it with you on slack.

2023-09-28 08:15 UTC, Kishan-Dhakan approved these changes

2023-09-28 08:15 UTC, merged