Fixing multiupload in zs3server by simplifying error handling and removing statuscallbacks
0chain/minio pull request #59
Opened 2023-08-12 11:09 UTC by sunilmhta

## Description
Some Refactoring in zs3server multiupload support:
1. Refactored the error to be returned as single error instead of `[]error` for consistency with other APIs.
2. Refactored the PutMultipleObject impl for zcn by removing the callbacks and removing the contentType.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2023-08-12 11:25 UTC, Hitenjain14 approved these changes
Revert changes made in go.mod, other than that LGTM.

2023-08-14 13:05 UTC, dabasov approved these changes
lgtm

2023-08-14 13:05 UTC, dabasov commented on go.mod
> +// replace github.com/0chain/gosdk => ../gosdk
remove it

2023-08-14 13:07 UTC, dabasov requested changes
lgtm

2023-08-14 13:07 UTC, dabasov commented on cmd/gateway/zcn/gateway-zcn.go
> +	errCh := make(chan error)
you can't remove size, since goroutine will hang on writ and never call wg.done(), main routine will never call channel close in that case

2023-08-14 16:41 UTC, sunilmhta commented on go.mod
> +// replace github.com/0chain/gosdk => ../gosdk
Reverted the changes in go.mod

2023-08-14 16:44 UTC, sunilmhta commented on cmd/gateway/zcn/gateway-zcn.go
> +	errCh := make(chan error)
This is not needed anymore because we are returning from upload if there is an error in path ref even for one file.

2023-08-14 19:52 UTC, dabasov approved these changes
Lgtm

2023-08-15 02:50 UTC, merged